# Generated by Django 3.2 on 2021-04-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_actual_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250, unique=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
